# API - Tools builder
To build and check api functionalties and build utility tools.

In [1]:
# here is the libraries we are going to use.
import pandas as pd             # to analyse data
import numpy as np              # for calculations
import seaborn as sn            # to visualise
import yaml                     # for reading yaml data easily.
import pyotp                    # to fatch live time TOTP used by shoonya api.
import os

print(f"Current working diretory is '{os.getcwd()}'. ")
print("Changing directory to root...")
# change current working dir to root
os.chdir("../")
print(f"Now the diretory is '{os.getcwd()}'. ")


# adding src/shoonya/ to path so that we can use shoonya module.
import sys
sys.path.append('src/shoonya/')

from api_helper import ShoonyaApiPy

# COUTION : DO NOT RUN this cell again after running it becouse it changes the path of current working directory.

Current working diretory is 'c:\My Files\Projects\python\algo-artha\notebooks'.
Changing directory to root...
Now the diretory is 'c:\My Files\Projects\python\algo-artha'.

### Login method
create ./config/cred.yaml file in the root folder, the cred.yaml file should contains followings:
```yaml
user    : <user-id>
pwd     : <password>
totptoken : <totp - token>
vc      : <vendor - code>
apikey  : <api - key>
imei    : <imei>
```

*For more information about shoonya api *[Github Page](https://github.com/Shoonya-Dev/ShoonyaApi-py)*.

In [2]:
# create a api instance
api = ShoonyaApiPy()

# raed cred.yaml data using yaml file.
with open('config/cred.yml') as f:
    cred = yaml.load(f, Loader=yaml.FullLoader)

# now loaging to api as follows.
ret = api.login(
    userid=cred['user'],
    password=cred['pwd'],
    twoFA=pyotp.TOTP(cred['totptoken']).now(),
    vendor_code=cred['vc'],
    api_secret=cred['apikey'],
    imei=cred['imei']
)

ret

{'request_time': '21:31:14 28-12-2023',
 'actid': 'FA133525',
 'access_type': ['WEB', 'TT', 'MOB', 'API'],
 'uname': 'MOHIT RAJ RATHOR',
 'prarr': [{'prd': 'C',
   's_prdt_ali': 'CNC',
   'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR']},
  {'prd': 'M',
   's_prdt_ali': 'NRML',
   'exch': ['NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']},
  {'prd': 'I',
   's_prdt_ali': 'MIS',
   'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX']},
  {'prd': 'H',
   's_prdt_ali': 'CO',
   'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']},
  {'prd': 'B',
   's_prdt_ali': 'BO',
   'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE']}],
 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']},
  {'exch': 'NIPO', 'prds': ['C']},
  {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']},
  {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']},
  {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']},
  {'exch': 'BCD', 'prds': ['M', 'I']},
  {'exch': 'MCX', 'prds': ['M', 'I', 'H', 'B']},
  {'exch': 'NCX', 'prds': ['M', 'I']},
  {'exch': 'BSTAR', 'prds': ['C']},
  {'exch': 'BFO', 'prds': ['M', 'I']}],
 'stat': 'Ok',
 'susertoken': 'ea36730b53320563e2eeb14ed0f92791e4dbcc81a48553ab9171592aa774cd9d',
 'email': 'mohitrajrathor@gmail.com',
 'uid': 'FA133525',
 'brnchid': 'HO',
 'totp_set': '1',
 'm_num': '9462443361',
 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'],
 'exarr': ['NSE',
  'NIPO',
  'NFO',
  'CDS',
  'BSE',
  'BCD',
  'MCX',
  'NCX',
  'BSTAR',
  'BFO'],
 'values': ['1', '2', '3', '4'],
 'mws': {'1': [{'exch': 'NSE',
    'token': '26009',
    'tsym': 'Nifty Bank',
    'instname': 'UNDIND',
    'pp': '2',
    'ls': '1',
    'ti': '0.05',
    'nontrd': '1'},
   {'exch': 'NSE',
    'token': '26000',
    'tsym': 'Nifty 50',
    'instname': 'UNDIND',
    'pp': '2',
    'ls': '1',
    'ti': '0.05',
    'nontrd': '1'}],
  '2': [{'exch': 'NSE',
    'token': '26074',
    'tsym': 'NIFTY MID SELECT',
    'instname': 'UNDIND',
    'pp': '2',
    'ls': '1',
    'ti': '0.05',
    'nontrd': '1'},
   {'exch': 'NSE',
    'token': '3045',
    'tsym': 'SBIN-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'}],
  '3': [{'exch': 'NSE',
    'token': '9408',
    'tsym': 'RAINBOW-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '399',
    'tsym': 'NIACL-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '15283',
    'tsym': 'KNRCON-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '513',
    'tsym': 'BOMDYEING-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'}],
  '4': [{'exch': 'NSE',
    'token': '2859',
    'tsym': 'RAYMOND-EQ',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'}]},
 'brkname': 'FINV',
 'lastaccesstime': '1703779274'}

In [3]:
 # tip : it is not convinent to view messy data like above, so to view it like that we can use pprint library as
from pprint import pprint

pprint(ret)

{'access_type': ['WEB', 'TT', 'MOB', 'API'],
 'actid': 'FA133525',
 'brkname': 'FINV',
 'brnchid': 'HO',
 'email': 'mohitrajrathor@gmail.com',
 'exarr': ['NSE',
           'NIPO',
           'NFO',
           'CDS',
           'BSE',
           'BCD',
           'MCX',
           'NCX',
           'BSTAR',
           'BFO'],
 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']},
              {'exch': 'NIPO', 'prds': ['C']},
              {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']},
              {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']},
              {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']},
              {'exch': 'BCD', 'prds': ['M', 'I']},
              {'exch': 'MCX', 'prds': ['M', 'I', 'H', 'B']},
              {'exch': 'NCX', 'prds': ['M', 'I']},
              {'exch': 'BSTAR', 'prds': ['C']},
              {'exch': 'BFO', 'prds': ['M', 'I']}],
 'lastaccesstime': '1703779274',
 'm_num': '9462443361',
 'mws': {'1': [{'exch': 'NSE',
                'instname': 'UNDIND',
                'ls': '1',
                'nontrd': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '26009',
                'tsym': 'Nifty Bank'},
               {'exch': 'NSE',
                'instname': 'UNDIND',
                'ls': '1',
                'nontrd': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '26000',
                'tsym': 'Nifty 50'}],
         '2': [{'exch': 'NSE',
                'instname': 'UNDIND',
                'ls': '1',
                'nontrd': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '26074',
                'tsym': 'NIFTY MID SELECT'},
               {'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '3045',
                'tsym': 'SBIN-EQ'}],
         '3': [{'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '9408',
                'tsym': 'RAINBOW-EQ'},
               {'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '399',
                'tsym': 'NIACL-EQ'},
               {'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '15283',
                'tsym': 'KNRCON-EQ'},
               {'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '513',
                'tsym': 'BOMDYEING-EQ'}],
         '4': [{'exch': 'NSE',
                'instname': 'EQ',
                'ls': '1',
                'pp': '2',
                'ti': '0.05',
                'token': '2859',
                'tsym': 'RAYMOND-EQ'}]},
 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'],
 'prarr': [{'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR'],
            'prd': 'C',
            's_prdt_ali': 'CNC'},
           {'exch': ['NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX'],
            'prd': 'M',
            's_prdt_ali': 'NRML'},
           {'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD', 'MCX', 'NCX'],
            'prd': 'I',
            's_prdt_ali': 'MIS'},
           {'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE'],
            'prd': 'H',
            's_prdt_ali': 'CO'},
           {'exch': ['NSE', 'NFO', 'CDS', 'MCX', 'BSE'],
            'prd': 'B',
            's_prdt_ali': 'BO'}],
 'request_time': '21:31:14 28-12-2023',
 'stat': 'Ok',
 'susertoken': 'ea36730b53320563e2eeb14ed0f92791e4dbcc81a48553ab9171592aa774cd9d',
 'totp_set': '1',
 'uid': 'FA133525',
 'uname': 'MOHIT RAJ RATHOR',
 'values': ['1', '2', '3', '4']}

In [4]:
# preetify printing connection status
"python".ljust(30, "-")

'python------------------------'

### View holding detailes

In [8]:
ret = api.get_quotes(token="23", exchange="NSE")
ret

{'request_time': '21:32:49 28-12-2023',
 'stat': 'Ok',
 'exch': 'NSE',
 'tsym': '67JK30-SG',
 'cname': 'SDL JK 6.7% 2030',
 'symname': '67JK30',
 'seg': 'EQT',
 'instname': 'SG',
 'isin': 'IN4920200073',
 'pp': '2',
 'ls': '100',
 'ti': '0.01',
 'mult': '1',
 'lut': '1703762613',
 'uc': '105.00',
 'lc': '95.00',
 'cutof_all': 'false',
 'prcftr_d': '(1 / 1 ) * (1 / 1)',
 'token': '23',
 'h': '0.00',
 'l': '0.00',
 'ap': '0.00',
 'o': '0.00',
 'v': '0',
 'ltq': '0',
 'ltt': '00:00:00',
 'ltd': '01-01-1980',
 'tbq': '0',
 'tsq': '0',
 'bp1': '0.00',
 'sp1': '0.00',
 'bp2': '0.00',
 'sp2': '0.00',
 'bp3': '0.00',
 'sp3': '0.00',
 'bp4': '0.00',
 'sp4': '0.00',
 'bp5': '0.00',
 'sp5': '0.00',
 'bq1': '0',
 'sq1': '0',
 'bq2': '0',
 'sq2': '0',
 'bq3': '0',
 'sq3': '0',
 'bq4': '0',
 'sq4': '0',
 'bq5': '0',
 'sq5': '0',
 'bo1': '0',
 'so1': '0',
 'bo2': '0',
 'so2': '0',
 'bo3': '0',
 'so3': '0',
 'bo4': '0',
 'so4': '0',
 'bo5': '0',
 'so5': '0'}

In [18]:
# view it using pandas as 
pd.DataFrame(ret)

,stat,exch_tsym,upldprc,sell_amt,holdqty,npoadqty,benqty,s_prdt_ali,prd,btstqty,usedqty,trdqty
0,Ok,"[{'exch': 'NSE', 'token': '14450', 'tsym': 'IB...",80.60,0.000000,0,1,0,CNC,C,0,0,0
1,Ok,"[{'exch': 'NSE', 'token': '17520', 'tsym': 'RT...",10.00,0.000000,0,5,0,CNC,C,0,0,0
2,Ok,"[{'exch': 'NSE', 'token': '18226', 'tsym': 'MA...",195.25,0.000000,0,1,0,CNC,C,0,0,0
3,Ok,"[{'exch': 'NSE', 'token': '10666', 'tsym': 'PN...",76.50,0.000000,0,1,0,CNC,C,0,0,0
4,Ok,"[{'exch': 'NSE', 'token': '17795', 'tsym': 'TR...",45.05,0.000000,0,2,0,CNC,C,0,0,0
5,Ok,"[{'exch': 'NSE', 'token': '15259', 'tsym': 'RP...",20.65,0.000000,0,5,0,CNC,C,0,0,0

### View position detailes

In [20]:
# to view intraday and option positions.
ret = api.get_positions()
type(ret)

# it show Nonetype if not position is held.

NoneType

### View orders

In [24]:
ret = api.get_order_book()
pd.DataFrame(ret)

,stat,norenordno,kidid,uid,actid,exch,tsym,qty,ordenttm,trantype,...,rprc,dscqty,brnchid,C,s_prdt_ali,prd,status,st_intrn,norentm,rqty
0,Ok,23122000605801,1,FA133525,FA133525,NFO,NIFTY21DEC23C21300,50,1703055571,B,...,0.00,0,HO,C,NRML,M,REJECTED,REJECTED,12:29:31 20-12-2023,0

### Get security info
requied fields :

In [30]:
ret = api.get_quotes(token="22", exchange="NSE")
pprint(ret)

{'ap': '2197.91',
 'bo1': '1',
 'bo2': '2',
 'bo3': '4',
 'bo4': '2',
 'bo5': '1',
 'bp1': '2190.65',
 'bp2': '2190.55',
 'bp3': '2190.50',
 'bp4': '2190.45',
 'bp5': '2190.20',
 'bq1': '4',
 'bq2': '3',
 'bq3': '13',
 'bq4': '3',
 'bq5': '2',
 'c': '2202.75',
 'cname': 'ACC LIMITED',
 'cutof_all': 'false',
 'exch': 'NSE',
 'h': '2217.05',
 'instname': 'EQ',
 'isin': 'INE012A01025',
 'l': '2185.00',
 'lc': '1982.50',
 'lp': '2191.20',
 'ls': '1',
 'ltd': '20-12-2023',
 'ltq': '1',
 'ltt': '12:44:23',
 'lut': '1703056474',
 'mult': '1',
 'o': '2209.00',
 'pp': '2',
 'prcftr_d': '(1 / 1 ) * (1 / 1)',
 'request_time': '12:44:35 20-12-2023',
 'seg': 'EQT',
 'so1': '1',
 'so2': '3',
 'so3': '2',
 'so4': '2',
 'so5': '1',
 'sp1': '2191.25',
 'sp2': '2191.45',
 'sp3': '2191.95',
 'sp4': '2192.00',
 'sp5': '2192.05',
 'sq1': '15',
 'sq2': '7',
 'sq3': '35',
 'sq4': '34',
 'sq5': '5',
 'stat': 'Ok',
 'symname': 'ACC',
 'tbq': '54267',
 'ti': '0.05',
 'toi': '9251100',
 'token': '22',
 'tsq': '82095',
 'tsym': 'ACC-EQ',
 'uc': '2423.00',
 'v': '419791',
 'wk52_h': '2645.95',
 'wk52_l': '1592.35'}